name: Alphanet testing

on:
  push:

jobs:
  batch-transactions:
    runs-on: ubuntu-latest
    if: ${{ true }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Node Cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Testcase - Pancakeswap
      working-directory: testcases/pancakeswap-contracts-godwoken
      run: |
        curl cip.cc

        yarn && yarn compile
        ENV_PATH=./alphanet.env yarn ts-node ./scripts/batch-transactions.ts
      timeout-minutes: 6
